#version 450
#extension GL_ARB_separate_shader_objects : require
uniform sampler2D InSampler;
layout(location = 0) in vec2 texCoord;
layout(location = 0) out vec4 fragColor;

uint readWord(ivec2 pixel) {
    uvec4 b = uvec4(texelFetch(InSampler, pixel, 0) * 255.0 + 0.5);
    return b.r | (b.g << 8u) | (b.b << 16u) | (b.a << 24u);
}
uint reducePairs(uint word) {
    // Only the high bit of each 2-bit confidence means occupied (levels 2/3).
    // Collapse two adjacent fine cells into one coarse cell, then fill both bits.
    uint v = ((word >> 1u) | (word >> 3u)) & 0x11111111u;
    v = (v | (v >> 2u)) & 0x05050505u;
    v = (v | (v >> 4u)) & 0x00550055u;
    v = (v | (v >> 8u)) & 0x00005555u;
    return v | (v << 1u);
}
void main() {
    // Dynamic cache is cubic. Static mip levels are generated by the exporter.
    int n = textureSize(InSampler, 0).y;
    int outColumns = n / 32;
    ivec2 p = ivec2(gl_FragCoord.xy);
    int columns = n / 16;
    ivec2 first = ivec2((p.x % outColumns) * 2 + columns * (p.x / outColumns) * 2, p.y * 2);
    uint low = 0u, high = 0u;
    // A coarse word's 128 children occupy only eight fine words: 2X * 2Y * 2Z.
    for (int z = 0; z < 2; ++z) {
        for (int y = 0; y < 2; ++y) {
            ivec2 pixel = first + ivec2(z * columns, y);
            low |= readWord(pixel);
            high |= readWord(pixel + ivec2(1, 0));
        }
    }
    uint result = reducePairs(low) | (reducePairs(high) << 16u);
    fragColor = vec4(result & 255u, (result >> 8u) & 255u,
                     (result >> 16u) & 255u, result >> 24u) / 255.0;
}
