#version 450
#extension GL_ARB_separate_shader_objects : require
#include <minecraft:globals.glsl>
#include <chroma:voxel_space.glsl>
uniform sampler2D InSampler;
layout(location = 0) flat in int cameraValid;
layout(location = 12) flat in int historyValid;
layout(location = 13) flat in ivec3 previousOrigin;
layout(location = 14) flat in uint frame;
layout(location = 0) out vec4 fragColor;

uint readWord(ivec2 pixel) {
    uvec4 b = uvec4(texelFetch(InSampler, pixel, 0) * 255.0 + 0.5);
    return b.r | (b.g << 8u) | (b.b << 16u) | (b.a << 24u);
}
uint reducePairs(uint word) {
    // Only the high bit of each 2-bit confidence means occupied (levels 2/3).
    // Collapse two adjacent fine cells into one coarse cell, then fill both bits.
    uint v = ((word >> 1u) | (word >> 3u)) & 0x11111111u;
    v = (v | (v >> 2u)) & 0x05050505u;
    v = (v | (v >> 4u)) & 0x00550055u;
    v = (v | (v >> 8u)) & 0x00005555u;
    return v | (v << 1u);
}
void main() {
    if (textureSize(InSampler, 0).y == 16384) {
        if (cameraValid == 0) discard;
        // Dynamic base: four observed surface records per quarter-cell. Upper levels
        // retain the compact two-bit confidence layout used by the DDA.
        ivec2 p = ivec2(gl_FragCoord.xy);
        ivec3 first = ivec3((p.x % 8) * 32, p.y * 2, (p.x / 8) * 2);
        ivec3 origin = chromaVoxOrigin();
        ivec3 firstWorld = origin + ((first - origin) & (CHROMA_VOX_N - 1));
        bool sameWindow = all(equal(origin, previousOrigin));
        // Rebuild the entire first LOD whenever the window moves. With an
        // unchanged window, every child keeps its world identity even when
        // this storage word crosses the window's toroidal X boundary.
        bool retained = historyValid != 0 && sameWindow;
        // Origins are multiples of four and this group starts at even Z, so
        // both Z children share z>>3. The acquisition phase is X-independent.
        bool updateSlice = chromaVoxUpdateSlice(firstWorld, frame)
            || chromaVoxUpdateSlice(firstWorld + ivec3(0, 1, 0), frame);
        if (retained && !updateSlice) discard;
        uint result = 0u;
        for (int i = 0; i < 16; ++i) {
            bool occupied = false;
            for (int child = 0; child < 8; ++child) {
                ivec3 v = first + ivec3(i * 2 + (child & 1), (child >> 1) & 1, child >> 2);
                int index = v.x + 256 * (v.y + 256 * v.z);
                int record = index * 4;
                for (int slot = 0; slot < 4; ++slot) {
                    uint word = readWord(ivec2((record + slot) & 4095, (record + slot) >> 12));
                    occupied = occupied || (word & 0x80000000u) != 0u
                        || ((word & 0x40000000u) != 0u && ((word >> 14u) & 65535u) != 0u);
                }
            }
            if (occupied) result |= 3u << uint(i * 2);
        }
        fragColor = vec4(result & 255u, (result >> 8u) & 255u,
                         (result >> 16u) & 255u, result >> 24u) / 255.0;
        return;
    }
    // Dynamic cache is cubic. Static mip levels are generated by the exporter.
    int n = textureSize(InSampler, 0).y;
    int outColumns = n / 32;
    ivec2 p = ivec2(gl_FragCoord.xy);
    int columns = n / 16;
    ivec2 first = ivec2((p.x % outColumns) * 2 + columns * (p.x / outColumns) * 2, p.y * 2);
    uint low = 0u, high = 0u;
    // A coarse word's 128 children occupy only eight fine words: 2X * 2Y * 2Z.
    for (int z = 0; z < 2; ++z) {
        for (int y = 0; y < 2; ++y) {
            ivec2 pixel = first + ivec2(z * columns, y);
            low |= readWord(pixel);
            high |= readWord(pixel + ivec2(1, 0));
        }
    }
    uint result = reducePairs(low) | (reducePairs(high) << 16u);
    fragColor = vec4(result & 255u, (result >> 8u) & 255u,
                     (result >> 16u) & 255u, result >> 24u) / 255.0;
}
